name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the selected branch
  push:
    branches: [ beamracer-ramexp ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Clone CC65
      - name: CC65 clone
        run: git clone https://github.com/cc65/cc65.git
      
      # make and install CC65
      - name: CC65 make
        run: cd cc65 && make && sudo PREFIX=/usr/local make install && cd ..

      # make beamracer variant
      - name: Build GEOS-beamracer
        run: make VARIANT=beamracer
